import React from "react";
import Layout from "../../components/layout/Layout";

const PrivacyPolicy = () => {
  return (
    <Layout>
      <div className="bg-gray-900 text-white p-6 min-h-screen">
        <div className="max-w-5xl mx-auto">
          <h1 className="text-4xl font-bold mb-4">Privacy Policy</h1>
          <p className="mb-6">Last updated: January 10, 2025</p>

          <p className="mb-6">
            This Privacy Policy describes Our policies and procedures on the
            collection, use and disclosure of Your information when You use the
            Service and tells You about Your privacy rights and how the law
            protects You.
          </p>
          <p className="mb-6">
            We use Your Personal data to provide and improve the Service. By
            using the Service, You agree to the collection and use of
            information in accordance with this Privacy Policy. This Privacy
            Policy has been created with the help of the{" "}
            <a
              href="https://www.termsfeed.com/privacy-policy-generator/"
              target="_blank"
              rel="noopener noreferrer"
              className="text-blue-400 underline"
            >
              Privacy Policy Generator
            </a>
            .
          </p>

          <h2 className="text-2xl font-semibold mt-8 mb-4">
            Interpretation and Definitions
          </h2>
          <h3 className="text-xl font-semibold mb-4">Interpretation</h3>
          <p className="mb-6">
            The words of which the initial letter is capitalized have meanings
            defined under the following conditions. The following definitions
            shall have the same meaning regardless of whether they appear in
            singular or in plural.
          </p>

          <h3 className="text-xl font-semibold mb-4">Definitions</h3>
          <p className="mb-4">For the purposes of this Privacy Policy:</p>
          <ul className="list-disc list-inside mb-6 space-y-2">
            <li>
              <strong>Account:</strong> A unique account created for You to
              access our Service or parts of our Service.
            </li>
            <li>
              <strong>Affiliate:</strong> An entity that controls, is controlled
              by or is under common control with a party, where "control" means
              ownership of 50% or more of the shares, equity interest or other
              securities entitled to vote for election of directors or other
              managing authority.
            </li>
            <li>
              <strong>Company:</strong> (referred to as either "the Company",
              "We", "Us" or "Our" in this Agreement) refers to Soft Game Studio.
            </li>
            <li>
              <strong>Cookies:</strong> Small files that are placed on Your
              computer, mobile device or any other device by a website,
              containing the details of Your browsing history on that website
              among its many uses.
            </li>
            <li>
              <strong>Country:</strong> Refers to: Punjab, India.
            </li>
            <li>
              <strong>Device:</strong> Any device that can access the Service
              such as a computer, a cellphone, or a digital tablet.
            </li>
            <li>
              <strong>Personal Data:</strong> Any information that relates to an
              identified or identifiable individual.
            </li>
            <li>
              <strong>Service:</strong> Refers to the Website.
            </li>
            <li>
              <strong>Service Provider:</strong> Any natural or legal person who
              processes the data on behalf of the Company. It refers to
              third-party companies or individuals employed by the Company to
              facilitate the Service, to provide the Service on behalf of the
              Company, to perform services related to the Service, or to assist
              the Company in analyzing how the Service is used.
            </li>
            <li>
              <strong>Usage Data:</strong> Data collected automatically, either
              generated by the use of the Service or from the Service
              infrastructure itself (for example, the duration of a page visit).
            </li>
            <li>
              <strong>Website:</strong> Refers to Soft Game Studio, accessible
              from{" "}
              <a
                href="https://softgamestudio.web.app"
                target="_blank"
                rel="noopener noreferrer"
                className="text-blue-400 underline"
              >
                https://softgamestudio.web.app
              </a>
            </li>
            <li>
              <strong>You:</strong> The individual accessing or using the
              Service, or the company, or other legal entity on behalf of which
              such individual is accessing or using the Service, as applicable.
            </li>
          </ul>

          <h2 className="text-2xl font-semibold mt-8 mb-4">
            Collecting and Using Your Personal Data
          </h2>
          <h3 className="text-xl font-semibold mb-4">
            Types of Data Collected
          </h3>

          <h4 className="text-lg font-semibold mb-2">Personal Data</h4>
          <p className="mb-6">
            While using Our Service, We may ask You to provide Us with certain
            personally identifiable information that can be used to contact or
            identify You. Personally identifiable information may include, but
            is not limited to:
          </p>
          <ul className="list-disc list-inside mb-6 space-y-2">
            <li>Email address</li>
            <li>First name and last name</li>
            <li>Phone number</li>
            <li>Address, State, Province, ZIP/Postal code, City</li>
            <li>Usage Data</li>
          </ul>

          {/* Add more content sections here */}

          <p className="mt-8">
            For more information about our privacy practices, visit our website
            or contact us at{" "}
            <a
              href="https://softgamestudio.web.app/ContactUs"
              target="_blank"
              rel="noopener noreferrer"
              className="text-blue-400 underline"
            >
              Contact Us
            </a>
            .
          </p>
        </div>
      </div>
    </Layout>
  );
};

export default PrivacyPolicy;
